package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/printer"
	"go/token"
	"slices"
	"strings"
)

// generatedHeader は、生成物の 1 行目。人間向けの表示で、検査の根拠にはしない (検査は、期待する内容との完全一致)。
const generatedHeader = "<!-- Code generated by tools/docgen from Go doc comments; DO NOT EDIT. Regenerate with `make docs`. -->"

// pkgDoc は、go/doc で得た、package の文書。
type pkgDoc struct {
	Src  *pkgSource
	Name string
	Fset *token.FileSet
	Pkg  *doc.Package
}

// isCommand は、package main か。
func (d *pkgDoc) isCommand() bool { return d.Name == "main" }

// outPath は、この package の生成物の path (repo 相対)。ディレクトリの構成を、そのまま写す。
func (d *pkgDoc) outPath() string { return referenceDir + "/" + d.Src.Dir + ".md" }

// buildDoc は、package を構文解析し、exported だけの文書 (doc.Mode 0) を作る。
func buildDoc(s *sources, p *pkgSource) (*pkgDoc, error) {
	pp, err := parsePackage(s, p)
	if err != nil {
		return nil, err
	}
	pkg, err := doc.NewFromFiles(pp.Fset, pp.Files, p.ImportPath)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", p.Dir, err)
	}
	return &pkgDoc{Src: p, Name: pp.Name, Fset: pp.Fset, Pkg: pkg}, nil
}

// renderer は、1 つの package の文書を Markdown にする。
// 入力由来の文字列 (doc comment の本文・識別子・path・URL・宣言) は、すべて normalize を通してから出力に入れる。
type renderer struct {
	d    *pkgDoc
	syms map[string]bool // 文書に出す識別子の anchor (Name か Type.Method)
}

func newRenderer(d *pkgDoc) *renderer {
	r := &renderer{d: d, syms: map[string]bool{}}
	addValues := func(vs []*doc.Value) {
		for _, v := range vs {
			for _, n := range v.Names {
				r.syms[n] = true
			}
		}
	}
	addFuncs := func(fs []*doc.Func) {
		for _, f := range fs {
			r.syms[anchorID(f.Recv, f.Name)] = true
		}
	}
	addValues(d.Pkg.Consts)
	addValues(d.Pkg.Vars)
	addFuncs(d.Pkg.Funcs)
	for _, t := range d.Pkg.Types {
		r.syms[t.Name] = true
		addValues(t.Consts)
		addValues(t.Vars)
		addFuncs(t.Funcs)
		addFuncs(t.Methods)
	}
	return r
}

// recvBase は、メソッドの受け取り側 ("*T" や "T[P]") から、型の名前 T を返す。関数なら空。
func recvBase(recv string) string {
	recv = strings.TrimPrefix(recv, "*")
	if i := strings.Index(recv, "["); i >= 0 {
		recv = recv[:i]
	}
	return recv
}

// anchorID は、識別子の anchor の id。関数・型・定数・変数は Name、メソッドは Type.Method。
func anchorID(recv, name string) string {
	if base := recvBase(recv); base != "" {
		return base + "." + name
	}
	return name
}

// anchors は、識別子の anchor (<a id="..."></a>) を並べる。id は、識別子として検査する。
func anchors(ids ...string) (string, error) {
	var b strings.Builder
	for _, id := range ids {
		for _, part := range strings.Split(id, ".") {
			if _, err := normalize(kindIdent, part); err != nil {
				return "", err
			}
		}
		b.WriteString(`<a id="` + id + `"></a>`)
	}
	return b.String(), nil
}

// flatten は、行内の部品から、装飾を除いた文字列を得る。
func flatten(ts []comment.Text) string {
	var b strings.Builder
	for _, t := range ts {
		switch x := t.(type) {
		case comment.Plain:
			b.WriteString(string(x))
		case comment.Italic:
			b.WriteString(string(x))
		case *comment.Link:
			b.WriteString(flatten(x.Text))
		case *comment.DocLink:
			b.WriteString(flatten(x.Text))
		}
	}
	return b.String()
}

// inline は、行内の部品を、Markdown の 1 行内の文字列にする。未知の部品は error にする (黙って落とさない)。
func (r *renderer) inline(ts []comment.Text) (string, error) {
	var b strings.Builder
	for _, t := range ts {
		switch x := t.(type) {
		case comment.Plain:
			s, err := normalize(kindText, string(x))
			if err != nil {
				return "", err
			}
			b.WriteString(s)
		case comment.Italic:
			s, err := normalize(kindText, string(x))
			if err != nil {
				return "", err
			}
			if strings.TrimSpace(s) != "" {
				b.WriteString("*" + s + "*")
			}
		case *comment.Link:
			label, err := r.inline(x.Text)
			if err != nil {
				return "", err
			}
			u, err := normalize(kindURL, x.URL)
			if err != nil {
				return "", err
			}
			b.WriteString("[" + label + "](" + u + ")")
		case *comment.DocLink:
			span, err := normalize(kindSpan, flatten(x.Text))
			if err != nil {
				return "", err
			}
			id := anchorID(x.Recv, x.Name)
			if (x.ImportPath == "" || x.ImportPath == r.d.Src.ImportPath) && r.syms[id] {
				b.WriteString("[" + span + "](#" + id + ")")
			} else {
				b.WriteString(span)
			}
		default:
			return "", fmt.Errorf("未知の行内の部品 %T", t)
		}
	}
	return b.String(), nil
}

// blocks は、doc comment の本文を、Markdown のブロックの列にする。見出しは、level 個の # にする。
// リンク定義は、参照されるものも、されないものも、リンク先を検査する。
func (r *renderer) blocks(text string, level int) ([]string, error) {
	if strings.TrimSpace(text) == "" {
		return nil, nil
	}
	cd := r.d.Pkg.Parser().Parse(text)
	for _, l := range cd.Links {
		if _, err := normalize(kindURL, l.URL); err != nil {
			return nil, err
		}
	}
	var out []string
	for _, blk := range cd.Content {
		switch x := blk.(type) {
		case *comment.Paragraph:
			line, err := r.inline(x.Text)
			if err != nil {
				return nil, err
			}
			if line = strings.TrimSpace(line); line != "" {
				out = append(out, line)
			}
		case *comment.Heading:
			line, err := r.inline(x.Text)
			if err != nil {
				return nil, err
			}
			out = append(out, strings.Repeat("#", level)+" "+strings.TrimSpace(line))
		case *comment.Code:
			code, err := normalize(kindCodeBlock, x.Text)
			if err != nil {
				return nil, err
			}
			out = append(out, code)
		case *comment.List:
			list, err := r.list(x)
			if err != nil {
				return nil, err
			}
			out = append(out, list)
		default:
			return nil, fmt.Errorf("未知の本文の部品 %T", blk)
		}
	}
	return out, nil
}

// list は、リスト 1 つを、Markdown にする。番号は数字だけ。項目の中は、段落だけ。
func (r *renderer) list(l *comment.List) (string, error) {
	var b strings.Builder
	for i, item := range l.Items {
		if i > 0 {
			b.WriteByte('\n')
			if l.BlankBetween() {
				b.WriteByte('\n')
			}
		}
		marker := "- "
		if item.Number != "" {
			if n := digitRun(item.Number); n == 0 || n != len(item.Number) || n > 9 {
				return "", fmt.Errorf("リストの番号 %q が数字ではない", item.Number)
			}
			marker = item.Number + ". "
		}
		wrote := false
		for _, blk := range item.Content {
			p, ok := blk.(*comment.Paragraph)
			if !ok {
				return "", fmt.Errorf("リスト項目の中に、未知の部品 %T", blk)
			}
			line, err := r.inline(p.Text)
			if err != nil {
				return "", err
			}
			line = strings.TrimSpace(line)
			switch {
			case !wrote:
				b.WriteString(marker + line)
				wrote = true
			default:
				b.WriteString("\n\n" + strings.Repeat(" ", len(marker)) + line)
			}
		}
		if !wrote {
			b.WriteString(strings.TrimSpace(marker))
		}
	}
	return b.String(), nil
}

// elideValues は、var と const の、複数行にわたる初期値を "..." に置き換える (宣言の見た目だけ。AST を書き換える)。
// 表 (複合リテラル) の中のコメントは、go/doc が落とすので、そのまま出すと、コメントの無い劣化した複製になり、
// 正 (元のファイル) と食い違って見える。値は、宣言の位置 (元のファイル) を読む。
func (r *renderer) elideValues(node ast.Node) {
	gd, ok := node.(*ast.GenDecl)
	if !ok || (gd.Tok != token.VAR && gd.Tok != token.CONST) {
		return
	}
	for _, spec := range gd.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		for i, v := range vs.Values {
			if r.d.Fset.Position(v.Pos()).Line != r.d.Fset.Position(v.End()).Line {
				vs.Values[i] = &ast.Ident{Name: "..."}
			}
		}
	}
}

// decl は、宣言を、Go のコードブロックにする。parse 時の FileSet を使う (使わないと、1 行に潰れる)。
func (r *renderer) decl(node ast.Node) (string, error) {
	r.elideValues(node)
	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	if err := cfg.Fprint(&buf, r.d.Fset, node); err != nil {
		return "", err
	}
	return normalize(kindGoBlock, buf.String())
}

// entry は、宣言 1 つの節 (見出し・宣言・文書) を作る。ids は anchor の id。
func (r *renderer) entry(level int, label string, ids []string, node ast.Node, docText string) ([]string, error) {
	span, err := normalize(kindSpan, label)
	if err != nil {
		return nil, err
	}
	a, err := anchors(ids...)
	if err != nil {
		return nil, err
	}
	code, err := r.decl(node)
	if err != nil {
		return nil, err
	}
	out := []string{strings.Repeat("#", level) + " " + a + span, code}
	body, err := r.blocks(docText, level+1)
	if err != nil {
		return nil, err
	}
	return append(out, body...), nil
}

func (r *renderer) values(kw string, vs []*doc.Value, level int) ([]string, error) {
	var out []string
	for _, v := range vs {
		sec, err := r.entry(level, kw+" "+strings.Join(v.Names, ", "), v.Names, v.Decl, v.Doc)
		if err != nil {
			return nil, err
		}
		out = append(out, sec...)
	}
	return out, nil
}

func (r *renderer) funcs(fs []*doc.Func, level int) ([]string, error) {
	var out []string
	for _, f := range fs {
		label := "func " + f.Name
		if base := recvBase(f.Recv); base != "" {
			label = "func (" + base + ") " + f.Name
		}
		sec, err := r.entry(level, label, []string{anchorID(f.Recv, f.Name)}, f.Decl, f.Doc)
		if err != nil {
			return nil, err
		}
		out = append(out, sec...)
	}
	return out, nil
}

func (r *renderer) types(ts []*doc.Type, level int) ([]string, error) {
	var out []string
	for _, t := range ts {
		sec, err := r.entry(level, "type "+t.Name, []string{t.Name}, t.Decl, t.Doc)
		if err != nil {
			return nil, err
		}
		out = append(out, sec...)
		for _, part := range []func() ([]string, error){
			func() ([]string, error) { return r.values("const", t.Consts, level+1) },
			func() ([]string, error) { return r.values("var", t.Vars, level+1) },
			func() ([]string, error) { return r.funcs(t.Funcs, level+1) },
			func() ([]string, error) { return r.funcs(t.Methods, level+1) },
		} {
			sub, err := part()
			if err != nil {
				return nil, err
			}
			out = append(out, sub...)
		}
	}
	return out, nil
}

// noPackageDoc は、package doc が無い package の文書に出す文。docs-check が、別に、error にする。
const noPackageDoc = "(package doc が無い)"

// render は、package 1 つの文書 (Markdown のファイルの中身) を作る。
func (r *renderer) render() (string, error) {
	d := r.d
	if _, err := normalize(kindPath, d.Src.Dir); err != nil {
		return "", err
	}
	title, err := normalize(kindSpan, d.Src.Dir)
	if err != nil {
		return "", err
	}
	imp, err := normalize(kindSpan, d.Src.ImportPath)
	if err != nil {
		return "", err
	}
	if _, err := normalize(kindPath, d.Src.ImportPath); err != nil {
		return "", err
	}
	kw := "import path: "
	if d.isCommand() {
		kw = "コマンド (package main): "
	}
	blocks := []string{generatedHeader, "# " + title, kw + imp}

	body, err := r.blocks(d.Pkg.Doc, 2)
	if err != nil {
		return "", fmt.Errorf("package doc: %w", err)
	}
	if len(body) == 0 {
		body = []string{noPackageDoc}
	}
	blocks = append(blocks, body...)

	var api []string
	for _, part := range []func() ([]string, error){
		func() ([]string, error) { return r.values("const", d.Pkg.Consts, 3) },
		func() ([]string, error) { return r.values("var", d.Pkg.Vars, 3) },
		func() ([]string, error) { return r.funcs(d.Pkg.Funcs, 3) },
		func() ([]string, error) { return r.types(d.Pkg.Types, 3) },
	} {
		sec, err := part()
		if err != nil {
			return "", err
		}
		api = append(api, sec...)
	}
	if len(api) > 0 {
		blocks = append(blocks, "## API")
		blocks = append(blocks, api...)
	}
	return normalize(kindDocument, strings.Join(blocks, "\n\n")+"\n")
}

// synopsis は、package doc の最初の段落を、装飾の無い 1 行の文字列にする。無ければ空。
func synopsis(d *pkgDoc) (string, error) {
	cd := d.Pkg.Parser().Parse(d.Pkg.Doc)
	for _, blk := range cd.Content {
		if p, ok := blk.(*comment.Paragraph); ok {
			s, err := normalize(kindCell, flatten(p.Text))
			return strings.TrimSpace(s), err
		}
	}
	return "", nil
}

// renderRefIndex は、docs/reference/README.md の中身 (package の一覧) を作る。
func renderRefIndex(docs []*pkgDoc) (string, error) {
	blocks := []string{
		generatedHeader,
		"# リファレンス",
		"Go の doc comment から `tools/docgen` が生成した package の文書。手で編集しない (`make docs` で再生成する)。",
	}
	rows := []string{"| package | 概要 |", "|---|---|"}
	sorted := slices.Clone(docs)
	slices.SortFunc(sorted, func(a, b *pkgDoc) int { return strings.Compare(a.Src.Dir, b.Src.Dir) })
	for _, d := range sorted {
		span, err := normalize(kindSpan, d.Src.Dir)
		if err != nil {
			return "", err
		}
		u, err := normalize(kindURL, d.Src.Dir+".md")
		if err != nil {
			return "", err
		}
		syn, err := synopsis(d)
		if err != nil {
			return "", fmt.Errorf("%s: %w", d.Src.Dir, err)
		}
		if syn == "" {
			syn = noPackageDoc
		}
		rows = append(rows, "| ["+span+"]("+u+") | "+syn+" |")
	}
	blocks = append(blocks, strings.Join(rows, "\n"))
	return normalize(kindDocument, strings.Join(blocks, "\n\n")+"\n")
}
